### ISSUE TITLE
Mudora Book is not brandished from chest

### ISSUE THREAD

**Issue by Renkineko** [christopho/zelda_roth_se#28]
When you get the Mudora Book, the item is not brandished by the hero (empty sprite is brandished).

**Comment by christopho** [comment]
Fixed

**Comment by Renkineko** [comment]
Just tried with the downloadable version of the game (1.0.1), it's not fixed. Because you did a new version this morning and said fix yesterday, I assume the issue is not solved at all :p

**Comment by christopho** [comment]
Yes the fix was wrong, now it is really fixed in the development version.
